### ISSUE TITLE
Space Invaders Game

### ISSUE THREAD

**Issue by abhisheks008** [World-of-ML/Play-With-Python#10]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : Space Invaders Game</br>
:red_circle: **Aim** : Create a Space Invaders Game using Python programming language.</br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by shivamkgpian** [comment]
kindly assign this to me
Name-Shivam Dwivedi
Github:shivamkgpian
Email ID:shivamkval@gmail.com
Codepeak

**Comment by abhisheks008** [comment]
Please mention your approach you are going to use to solve this issue.

**Comment by aayushsinha0706** [comment]
Since this is still up for grabs
Please assign me this issue

Full name : AAYUSH SINHA
GitHub Profile Link : aayushsinha0706
Email ID : aayushsinha0706@outlook.com
Participant ID (if applicable):
Approach for this Project : I will be working through creating a full space shooter/invader game using pygame
What is your participant role? (Mention the Open Source program) : CODEPEAK 22

**Comment by abhisheks008** [comment]
Issue assigned to you @aayushsinha0706
