### ISSUE TITLE
Snake game

### ISSUE THREAD

**Issue by sankooru14** [World-of-ML/Play-With-Python#60]
### Play With Python Repository (Proposing new issue)
:red_circle: **Project Title** : </br>
:red_circle: **Aim** : </br>

**********************************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sankooru Manideep
- GitHub Profile Link : github.com/sankooru14
- Email ID :sankooru@iitg.ac.in
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)
- CODEPEAK22

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Snake game issue is already assigned to other contributor. That's why I told you to look after the issues before creating a new one. Here is the assigned snake game issue, https://github.com/World-of-ML/Play-With-Python/issues/5

You can come up with other issues, or you comment out on the existing unassigned issues present here.
@sankooru14
